# Minimal rsyslog config for the ot-hmi simulator. Splits authentication
# events to /var/log/auth.log so filebeat can ship them as system.auth
# events to Elastic.

auth,authpriv.*                 /var/log/auth.log
*.*;auth,authpriv.none          -/var/log/syslog
daemon.*                        -/var/log/daemon.log
